name: Deploy
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to'
        required: true
        default: 'live'
        type: choice
        options:
          - live

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  PNPM_VERSION: 9.12.3
  TF_VAR_env: live
  TF_VAR_zone_id: ${{ secrets.LIVE_ZONE_ID }}
  TF_VAR_root_domain: lhowsam.com
  TF_VAR_sub_domain: blurhash.lhowsam.com
  TF_VAR_private_key: ${{ secrets.LIVE_PRIVATE_KEY }}
  TF_VAR_certificate_body: ${{ secrets.LIVE_CERTIFICATE_BODY }}
  TF_VAR_certificate_chain: ${{ secrets.CERT_CHAIN }}
  TF_VAR_deployed_by: ${{ github.actor }}
  TF_VAR_git_sha: ${{ github.sha }}

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.env }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Fetch latest commits
        run: git fetch && git pull

      - name: Install
        uses: ./.github/actions/install

      - name: Validate
        uses: ./.github/actions/validate

      # - name: Changelogs
      #   uses: ./.github/actions/changelog

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: ${{ github.event.inputs.env }}
          aws-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

